#!/usr/bin/fish

set HEADSET (pactl list sinks | rg -B 2 bluez | sed 1q | tr -d \# | awk '{print $2}')

pactl set-sink-volume @DEFAULT_SINK@ -5% # ALSA sink

if test (count $HEADSET) -gt 0
    pactl set-sink-volume $HEADSET -5% # bluetooth
end

notify-send "Volume -5%"
