#!/usr/bin/env bash

# Script name: dm-wiki
# Description:
# Dependencies: dmenu, arch-wiki-docs

# Set with the flags "-e", "-u", "-o pipefail" cause the script to fail
# if certain things happen, which is a good thing. Otherwise, we can
# get hidden bugs that are hard to discover.
set -euo pipefail

wikidir="/usr/share/doc/arch-wiki/html"

wikipages() {
    wikidocs="$(find ${wikidir}"/en/" -iname "*.html")"
    choice=$(printf '%s\n' "${wikidocs[@]}" | \
           cut -d '/' -f8- | \
           sed -e 's/_/ /g' -e 's/.html//g' | \
           sort -g | \
           dmenu -l 20 -p 'Arch Wiki Docs: ' "$@") || exit 1

    if [ "$choice" ]; then
        article=$(printf '%s\n' "${wikidir}/en/${choice}.html" | sed 's/ /_/g')
        xdg-open "$article"
    else
        echo "Program terminated." && exit 0
    fi
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && wikipages "$@"
