#!/usr/bin/fish

set alsa (pactl list sinks | rg -B 2 alsa | sed 1q | tr -d \# | awk '{print $2}')

set headset (pactl list sinks | rg -B 2 bluez | sed 1q | tr -d \# | awk '{print $2}')

set headset_name (pactl list sinks | rg -B 2 bluez | rg device.description | cut -d '=' -f 2)

set default (pactl info | rg "Default Sink" | cut -d ' ' -f 3 )

if test (count (echo $default | rg alsa )) -gt 0
    if test (count $headset) -gt 0
        pactl set-default-sink $headset
        notify-send "Default sink set to $headset_name"
    end
else
    pactl set-default-sink $alsa
    notify-send "Default sink set to ALSA"
end
