# after-startup-command = ['exec-and-forget sketchybar']
# # Notify Sketchybar about workspace change
# exec-on-workspace-change = ['/bin/bash', '-c',
#   'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
#   'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
# ]

start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 100

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but acidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = false

# [[on-window-detected]]
# if.app-id = 'com.apple.systempreferences'
# if.app-name-regex-substring = 'settings'
# if.window-title-regex-substring = 'substring'
# if.workspace = 'workspace-name'
# if.during-aerospace-startup = true
# check-further-callbacks = true
# run = ['layout floating', 'move-node-to-workspace S']  # The callback itself

[[on-window-detected]]
if.app-name-regex-substring = 'finder'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'spark'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'fantastical'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'trello'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'spotify'
run = 'layout floating'

# For if.app-id, use "mdls -name kMDItemCFBundleIdentifier <path to *.app>" to find out the system name
[[on-window-detected]]
if.app-id = 'com.anthropic.claudefordesktop'
run = 'layout floating'

# Possible values: (qwerty|dvorak|colemak)
[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 20
    inner.vertical =   20
    outer.left =       20
    outer.bottom =     20
    outer.top =        10
    outer.right =      20 # 80

[mode.main.binding]

    # All possible keys:
    # - Letters.        a, b, c, ..., z
    # - Numbers.        0, 1, 2, ..., 9
    # - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
    # - F-keys.         f1, f2, ..., f20
    # - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
    #                   backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
    #                   backspace, tab, pageUp, pageDown, home, end, forwardDelete,
    #                   sectionSign (ISO keyboards only, european keyboards only)
    # - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
    #                   keypadMinus, keypadMultiply, keypadPlus
    # - Arrows.         left, down, up, right

    # All possible modifiers: cmd, alt, ctrl, shift

    # All possible commands: https://nikitabobko.github.io/AeroSpace/commands

    # App shortcuts
    alt-semicolon = 'exec-and-forget open -a /Applications/Ghostty.app'
    alt-o = 'exec-and-forget open -a /Applications/Obsidian.app'
    alt-m = 'exec-and-forget open -a /Applications/Spark Desktop.app/'
    alt-c = 'exec-and-forget open -a /Applications/Fantastical.app'
    alt-a = 'exec-and-forget open -a /Applications/Arc.app'
    alt-i = 'exec-and-forget open -a /Applications/Claude.app'

    alt-ctrl-f = 'fullscreen'
    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

    alt-shift-left = ['join-with left', 'mode main']
    alt-shift-down = ['join-with down', 'mode main']
    alt-shift-up = ['join-with up', 'mode main']
    alt-shift-right = ['join-with right', 'mode main']


    # See: https://nikitabobko.github.io/AeroSpace/commands#focus
    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move
    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#resize
    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace
    alt-q= 'workspace 1'
    alt-w= 'workspace 2'
    alt-e= 'workspace 3'
    alt-r= 'workspace 4'
    alt-t= 'workspace 5'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
    alt-shift-q= 'move-node-to-workspace 1'
    alt-shift-w= 'move-node-to-workspace 2'
    alt-shift-e= 'move-node-to-workspace 3'
    alt-shift-r= 'move-node-to-workspace 4'
    alt-shift-t= 'move-node-to-workspace 5'

    alt-tab = 'workspace-back-and-forth'
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    alt-shift-semicolon = 'mode service'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # reset layout
    backspace = ['close-all-windows-but-current', 'mode main']

    # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
    #s = ['layout sticky tiling', 'mode main']
