#     _    _                 _ _____ _______   __
#    / \  | | __ _  ___ _ __(_)_   _|_   _\ \ / /
#   / _ \ | |/ _` |/ __| '__| | | |   | |  \ V /
#  / ___ \| | (_| | (__| |  | | | |   | |   | |
# /_/   \_\_|\__,_|\___|_|  |_| |_|   |_|   |_|
#
# See this wiki page for more info:
# https://github.com/jwilm/alacritty/wiki

env:
  TERM: xterm-256color

# Window configurations
window:
  opacity: 0.8

  dimensions:
    columns: 0
    lines: 0

  padding:
    x: 0
    y: 0

  decorations: full

  dynamic_title: true

  dynamic_padding: true

    # Window class (Linux/BSD only):
  class:
    # Application instance name
    instance: Alacritty
    # General application class
    general: Alacritty

scrolling:
  history: 10000
  multiplier: 3

# Font configurations
font:
  size: 12
  normal:
    family: FiraCode Nerd Font
  bold:
    family: FiraCode Nerd Font
  italic:
    family: FiraCode Nerd Font
  bold_italic:
    family: FiraCode Nerd Font
    size: 11

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  scale_with_dpi: true

draw_bold_text_with_bright_colors: true

# ...
# Visual Bell
# ...

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  faux_scrolling_lines: 1
  hide_when_typing: true

cursor:
  # Values for `style`:
  #   - ▇ Block
  #         - unfocused_hollow: true
  #   - _ Underline
  #   - | Beam
  style: Underline

live_config_reload: true

shell:
  program: /usr/bin/fish

url:
  launcher:
    program: qutebrowser
    args: []
  modifiers: Control

log_level: Error
persistent_logging: false

# Keybindings
key_bindings:
  - { key: Y,              mods: Control, action: Paste                      }
  - { key: W,              mods: Alt,     action: Copy                       }
  - { key: Insert,         mods: Shift,   action: PasteSelection             }
  - { key: Key0,           mods: Control, action: ResetFontSize              }
  - { key: Equals,         mods: Control, action: IncreaseFontSize           }
  - { key: NumpadAdd,      mods: Control, action: IncreaseFontSize           }
  - { key: NumpadSubtract, mods: Control, action: DecreaseFontSize           }
  - { key: Minus,          mods: Control, action: DecreaseFontSize           }
  - { key: Return,         mods: Alt,     action: ToggleFullscreen           }
  - { key: Paste,                         action: Paste                      }
  - { key: Copy,                          action: Copy                       }
  - { key: L,              mods: Control, action: ClearLogNotice             }
  - { key: L,              mods: Control, chars: "\x0c"                      }
  - { key: PageUp,         mods: Shift,   action: ScrollPageUp,   mode: ~Alt }
  - { key: PageDown,       mods: Shift,   action: ScrollPageDown, mode: ~Alt }
  - { key: Home,           mods: Shift,   action: ScrollToTop,    mode: ~Alt }
  - { key: End,            mods: Shift,   action: ScrollToBottom, mode: ~Alt }
#  - { key: D,              mods: Control, chars: "\x1b[3~"                   }

# KDE Breeze (Modified)
colors:
  # Default colors
  primary:
    background: '#232627'
    foreground: '#fcfcfc'

    dim_foreground: '#eff0f1'
    bright_foreground: '#ffffff'
    dim_background: '#31363b'
    bright_background: '#000000'

  # Normal colors
  normal:
    black: '#232627'
    red: '#ee4035'
    green: '#6bd36e'
    yellow: '#f37736'
    blue: '#0392cf'
    magenta: '#9b59b6'
    cyan: '#1abc9c'
    white: '#fcfcfc'

  # Bright colors
  bright:
    black: '#7f8c8d'
    red: '#c0392b'
    green: '#7bc043'
    yellow: '#fdf498'
    blue: '#3daee9'
    magenta: '#8e44ad'
    cyan: '#16a085'
    white: '#ffffff'

  # Dim colors
  dim:
    black: '#31363b'
    red: '#783228'
    green: '#17a262'
    yellow: '#b65619'
    blue: '#1b668f'
    magenta: '#614a73'
    cyan: '#186c60'
    white: '#63686d'
